### PR TITLE
357 turn off n/no extraneous import

### PR DESCRIPTION
**Pull request by OmarJaroudi**

### CODE REVIEW

**Review by tagoro9 — COMMENTED** [review]
Could you add a bit of context why you are disabling it?

Maybe we could follow an approach like with `n/no-unpublished-import` where we disable it in the places that it makes sense to disable?

**Comment by OmarJaroudi** [comment]
@tagoro9 https://github.com/open-turo/eslint-config-typescript/issues/357
I couldn't get this rule to play well with importing static .json/.svg files + using aliasing e.g. `import translations from "~/en_US.json"` counts as extraneous. I felt that this will be a pattern that we will encounter in most of our TS repos. But now that I think about it, I think we can also disable it in the react config rather than here, because it's a much higher probability for a react project to have translations files or static assets.

**Comment by tagoro9** [comment]
@OmarJaroudi I wonder if there is a way to just disable it for those file patterns instead of across the board? Moving to the react config makes sense too!

**Comment by OmarJaroudi** [comment]
@tagoro9 Yeah I've been trying to debug with the available configs for this rule since yesterday.
Here's a compromise, I'll close this PR, disable it in the repo I was working on while I take another stab at whitelisting certain file paths, it's mainly the alias that is confusing eslint I think.
If I don't end up cracking it, I'll file a PR to disable it in the react preset instead of here

**Pull request closed without merging**
